services:
  backend:
    build:
      context: ./backend
    container_name: notes_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app

volumes:
  # No longer needed for external SQL Server
